### ISSUE TITLE
如何校验下载内容？

### ISSUE THREAD

**Issue by PussyCat0700** [esbatmop/MNBVC#11]
您好：

    我注意到下载列表只提供了链接，没有提供类似md5的校验码，想请教一下我应该如何校验本地下载文件与网盘文件的一致性呢？

十分感谢！

**Comment by esbatmop** [comment]
都是加了密码的压缩包，我理解加了密码的压缩包，只要有点错，就解压报错啦。

**Comment by xclimbing** [comment]
微力同步提供的下载都加上了md5校验码，但这也是我从百度网盘下载后才加上的。
