### ISSUE TITLE
如何处理json文件， 每个json文件格式不太一样？

### ISSUE THREAD

**Issue by Mddct** [esbatmop/MNBVC#12]
首先，非常感谢这个项目
现在有个疑问， “如何处理json文件， 每个json文件格式不太一样？”， 或者我去哪里可以找到对应的json字段定义呢？

感谢！

**Comment by esbatmop** [comment]
随着我们不断的清洗，json格式最终会趋于一致。目前同一个json文件内都肯定是一个格式，取第一行看一下即可。
