### ISSUE TITLE
hugging face上的jsonl.gz无法解压

### ISSUE THREAD

**Issue by guozhiyao** [esbatmop/MNBVC#13]
我直接下载了hugging face上的jsonl.gz文件，然后尝试用`gzip`和`gunzip`进行解压，但是文件貌似有点问题
<img width="304" alt="image" src="https://user-images.githubusercontent.com/21999339/230317699-be98117c-38ce-4af4-87a5-a04b1d845228.png">

**Comment by silverriver** [comment]
请问是哪个文件？
