### ISSUE TITLE
huggingface数据集

### ISSUE THREAD

**Issue by lwmlyy** [esbatmop/MNBVC#17]
hf上的分类数据集是微力或云盘的一个子集吗

**Comment by lwmlyy** [comment]
另外，20230320.zip云盘下载的文件内容是代码，中文语料为什么要包含大量github代码？

**Comment by silverriver** [comment]
> hf上的分类数据集是微力或云盘的一个子集吗

是的

**Comment by silverriver** [comment]
> 另外，20230320.zip云盘下载的文件内容是代码，中文语料为什么要包含大量github代码？

代码数据对于提升模型的性能有较大帮助，一个高质量的数据集应该包含着部分数据。

**Comment by esbatmop** [comment]
> 

在我们的AI观中，代码语料是核心。代码语料每个符号都有用，是最完美的语料。
