### ISSUE TITLE
请问MNBVC会跟Common Crawl有重叠部分吗

### ISSUE THREAD

**Issue by CoinCheung** [esbatmop/MNBVC#19]

**Comment by esbatmop** [comment]
包含common crawl数据

**Comment by CoinCheung** [comment]
@esbatmop 
请问huggingface hub上的数据和github的readme里面给的百度云链接数据的关系是什么样的呢，是否可以认为百度云里面的数据是会随时改变的，但是huggingface hub上面只做增量，并且已经上传的部分基本不会再修改了?
