### ISSUE TITLE
一人行快，众人行远

### ISSUE THREAD

**Issue by kingfs** [esbatmop/MNBVC#21]
摇人的话，至少留个联系方式？

**Comment by esbatmop** [comment]
联系方式需要动手找一下呢:)

**Comment by kingfs** [comment]
这个...  esbatmop@gmail.com

**Comment by esbatmop** [comment]
> 这个... [esbatmop@gmail.com](mailto:esbatmop@gmail.com)

不是这个，请看到本issue的同学不要被误导
