### ISSUE TITLE
百度网盘链接打不开了

### ISSUE THREAD

**Issue by geniuslinchao** [esbatmop/MNBVC#26]
网盘链接点过去显示“啊哦，你所访问的页面不存在了。”，所有链接都是如此。应该是近期调整导致的。

**Comment by esbatmop** [comment]
很古怪的问题，复制回README.md后链接就正常了，但是在baidupan.md中就不行。打开访问页面不存在对着url打回车就可以正常访问到，但是直接点刷新则不行。

**Comment by esbatmop** [comment]
搞定了，md文件名或md存放的目录里只要有“baidupan”关键词，就会被404，只要不带这个关键词就能正常跳转了。

**Comment by metangram** [comment]
@esbatmop Hi,

**Comment by aplmikex** [comment]
已经重新上传了。
