### ISSUE TITLE
用阿里云盘或者其他网盘？

### ISSUE THREAD

**Issue by hijkzzz** [esbatmop/MNBVC#29]
百度超级慢也不方便在服务器上下载

**Comment by libhot** [comment]
可以使用百度网盘Python客户端之类，在服务器上直接下载。
也可以把服务器的磁盘使用samba共享映射出来，这样台式机可以下载到这个共享目录。

**Comment by xclimbing** [comment]
> 百度超级慢也不方便在服务器上下载

目前条件所限，只能提供百度网盘及微力下载两种方式。关于百度网盘下载，充值一下会员可以有效提高下载速度及稳定性，或者，你也可以看一下网上其他跳过百度限制的下载方式，例如油猴脚本+IDM等。
