### ISSUE TITLE
现在已经清洗好10G了吗

### ISSUE THREAD

**Issue by Sweetclover** [esbatmop/MNBVC#33]

**Comment by esbatmop** [comment]
清洗好了

**Comment by Sweetclover** [comment]
是从5400G里清洗了10G吗，在hugging face上可以下载的那个10G吗
| |
15022435237
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月17日 17:17 |
| 收件人 | esbatmop/MNBVC ***@***.***> |
| 抄送人 | Sweetclover ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [esbatmop/MNBVC] 现在已经清洗好10G了吗 (Issue #33) |

清洗好了
