### ISSUE TITLE
huggingface百度网盘

### ISSUE THREAD

**Issue by zachluo** [esbatmop/MNBVC#36]
请问一下，huggingface上面清洗的数据有没有国内的下载地址，例如百度网盘之类的？谢谢。

**Comment by esbatmop** [comment]
如果连接huggingface下载数据集比较困难。
方案一：参考我们平行语料组组长jia li写的[小贴士](https://mp.weixin.qq.com/s/e_Krti4U7TxPuFWmUep80Q)
方案二：使用下面的脚本，获取可以访问的huggingface的ip，然后修改本机host。
`#!/usr/bin/env python
# -*- coding:utf-8 -*-
# 获取huggingface最快的ip，也可修改ip列表用于获取github等网站的最快ip
# author:明心
# 用法：python getHuggingfaceIp.py

import subprocess
import re
import platform
from tqdm import tqdm

# 设置超时时间.mac中单位为毫秒，设置到300;ubuntu中单位为秒，设为1
if platform.system() == 'Darwin':
    timeout = "300"
else:
    timeout = "1"

# 填写需要ping的IP地址列表，用逗号分隔
ip_list = "52.222.130.110,13.32.121.112,18.164.174.118,54.192.18.10,13.33.33.110,54.192.18.37,54.192.18.113,18.164.174.17,18.239.50.80,13.35.7.38,18.238.4.28,103.252.115.169,13.225.131.93,52.85.242.84,18.66.171.10,108.160.170.39,18.245.124.37,65.9.42.50,18.65.159.63,13.32.121.124,13.225.131.6,13.33.33.102,13.35.147.23,52.222.130.56,13.35.7.81,52.84.45.107,18.172.52.121,54.192.18.15,18.165.122.11,65.9.181.60"  # 填写需要ping的IP地址列表，用逗号分隔

ips = ip_list.split(",")
results = []

# 根据ping命令的执行结果，判断是否连接成功，并将连接速度存储到results列表中
for ip in tqdm(ips):
    ping = subprocess.Popen(
        ["ping", "-c", "1", "-n", "-W", timeout, ip],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )
    out, error = ping.communicate()

    if re.search("bytes from", out.decode()):
        time = re.search(r'time=(.*) ms', out.decode())
        if time:
            results.append((ip, float(time.group(1))))

#对results列表中的元素按连接速度排序
results.sort(key=lambda x: x[1])
#输出已按连接速度从快到慢排序的IP地址列表
print("下列ip已按连接速度从快到慢排序：")
for result in results:
    print(result[0] + " responded in " + str(result[1]) + "ms")`

**Comment by zachluo** [comment]
谢谢
