### ISSUE TITLE
oscar语料的一些问题

### ISSUE THREAD

**Issue by chinoll** [esbatmop/MNBVC#42]
记录在使用中发现的一些问题，部分语料没有清洗干净
![Image](https://github.com/esbatmop/MNBVC/assets/22575232/e2cf57ad-6247-4d65-ae75-008c92fe097b)
![2](https://github.com/esbatmop/MNBVC/assets/22575232/6017a4c0-664c-4e18-8be6-e50f699193f2)

**Comment by esbatmop** [comment]
#https://huggingface.co/datasets/liwu/MNBVC/discussions/12
