### ISSUE TITLE
wikipedia JSONDecodeError

### ISSUE THREAD

**Issue by TristanMeng** [esbatmop/MNBVC#46]
hello，
        我在使用Wikipedia数据时候，加载过程发现 下面这条数据会出现JSONDecodeError问题。

> {"文件名": "cleaned/zhwiki-20230320/folder_1/201103.txt", "是否待查文件": false, "是否重复文件": false, "文件大小": 1990, "simhash": 9264344694624880832, "最长段落长度": 135, "段落数": 24, "去重段落数": 24, "低质量段落数": 0, "段落": [{"行号": 0, "是否重复": false, "是否跨文件重复": false, "md5": "ef40abc35283594e0f23fa41038b0092", "内容": "【马泰奥·佩西纳】"}, {"行号": 2, "是否重复": false, "是否跨文件重复": false, "md5": "0bc16acb389ac1af1ad69f21699c9d0f", "内容": "马泰奥·佩西纳（Matteo Pessina，），意大利足球运动员，司职中场，目前效力于意甲俱乐部蒙沙并担任队长，同时代表意大利国家足球队参加国际比赛。"}, {"行号": 4, "是否重复": false, "是否跨文件重复": false, "md5": "27f7f59fc61d36fdf870883ae5d711c8", "内容": "==俱乐部生涯=="}, {"行号": 5, "是否重复": false, "是否跨文件重复": false, "md5": "f265bd0a7d184

下面的文件会出现UnicodeDecodeError问题

> gzip://25.jsonl::/MNBVC//wiki/20230197/25.jsonl.gz

**Comment by esbatmop** [comment]
已经修复，详见
https://huggingface.co/datasets/liwu/MNBVC/commit/b86f06f0abe256561ea1684cc611e362f28c1eae
和
https://huggingface.co/datasets/liwu/MNBVC/commit/279dda1ed0754c9ddeca5cb1cdd9251e271d6390
