### ISSUE TITLE
洗稿工具垃圾网页识别

### ISSUE THREAD

**Issue by chenhehong** [esbatmop/MNBVC#48]
> 野生智能和机械进修
网页数据中，出现一些和常见名词不同的说法

> 野生智能是指由机械经由过程特地设想的算法去了解、阐发战进修数据，从而充任人类思想蓝图的征象。
野生智能机械可以记着人类的举动形式并按照他们的爱好停止调解
实际上这段文字对应的应该是

> 人工智能是指机器通过专门设计的算法来理解、分析和学习数据，从而充当人类思维蓝图的现象。
人工智能机器能够记住人类的行为模式并根据他们的喜好进行调整。
研究发现出现这些说法，是自动替换文字的洗稿工具造成的。这些语料可以认为是机器产生的脏数据，且很难被识别出来。

请教一下，这种洗稿工具造成的垃圾网页，现在有什么工具或方法可以识别吗？

**Comment by esbatmop** [comment]
我们有个开发中的任务，是用绝对标准的语料（例如中文维基百科、中文论文、中文书籍等）生成一个很小的模型，作为绝对准确的中文用语规范模型，用来检查乱码和上述洗稿文章等非自然的中文数据。
