### ISSUE TITLE
wikipedia与code_metadata数据有误

### ISSUE THREAD

**Issue by fitexmage** [esbatmop/MNBVC#57]
在下载过程中又发现如下两个数据集有报错，请问可以麻烦再更新一下吗：
1. wikipedia数据集中的`https://huggingface.co/datasets/liwu/MNBVC/resolve/main/wiki/20230198/58.jsonl.gz`还有一个JSONDecodeError的问题
2. code_metadata数据集报错：`FileNotFoundError: Couldn't find file at https://huggingface.co/datasets/liwu/MNBVC/resolve/main/code/metadata/20230302/20000000-21000000.jsonl.gz`

**Comment by esbatmop** [comment]
麻烦@silverriver 看下

**Comment by silverriver** [comment]
> 在下载过程中又发现如下两个数据集有报错，请问可以麻烦再更新一下吗：
> 
> 1. wikipedia数据集中的`https://huggingface.co/datasets/liwu/MNBVC/resolve/main/wiki/20230198/58.jsonl.gz`还有一个JSONDecodeError的问题
> 2. code_metadata数据集报错：`FileNotFoundError: Couldn't find file at https://huggingface.co/datasets/liwu/MNBVC/resolve/main/code/metadata/20230302/20000000-21000000.jsonl.gz`

已经修复了这两个问题
