### ISSUE TITLE
20230130.zip 貌似在百度网盘上被举报了

### ISSUE THREAD

**Issue by silverriver** [esbatmop/MNBVC#7]
此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！ 

https://pan.baidu.com/s/1rmKj0GNYsgrcgJzS2Z0B3A?pwd=b27c

**Comment by esbatmop** [comment]
收到，现在正在把所有包都重新清洗加密打包。可以等一周，或先使用微力下载。

**Comment by esbatmop** [comment]
链接修复了，所有历史包都清洗数据后重新打过了。
