### ISSUE TITLE
求种子文件链接，现在只有百度网盘

### ISSUE THREAD

**Issue by hejunqing** [esbatmop/MNBVC#9]
按照readme，种子链接应该3月1日才失效，但是现在只有百度网盘了，下载很慢。求更新链接~

**Comment by esbatmop** [comment]
你看下git commit的历史。。。往上翻一下。或者等两天，等我们准备好新的下载方式。

**Comment by esbatmop** [comment]
提供了http下载方式：http://dl.mnbvc.253874.net:9191/mnbvc/
稍后会更新到readme

**Comment by xclimbing** [comment]
目前只有百度网盘和微力同步两种下载方式，数据量太大了，web下载方式找不到空间。
